In [100]:
import glob
import pandas as pd
import os

In [101]:
# Find all CSV files in the target directory
file_path = "C:/Users/mohit/Desktop/lego data/*.csv"
all_files = glob.glob(file_path)

In [102]:
# Load into a dictionary
df_dict = {os.path.basename(f): pd.read_csv(f) for f in all_files}

In [103]:
# View a specific file's data
df_dict["1970.csv"].columns

Index(['setID', 'number', 'numberVariant', 'name', 'year', 'theme',
       'themeGroup', 'subtheme', 'category', 'released', 'pieces',
       'bricksetURL', 'rating', 'reviewCount', 'packagingType', 'availability',
       'thumbnailURL', 'imageURL', 'height', 'width', 'depth', 'weight'],
      dtype='object')

In [104]:
# View a specific file's data
df_dict["2025.csv"].columns

Index(['setID', 'number', 'numberVariant', 'name', 'year', 'theme',
       'themeGroup', 'subtheme', 'category', 'released', 'pieces', 'minifigs',
       'bricksetURL', 'rating', 'reviewCount', 'packagingType', 'availability',
       'agerange_min', 'thumbnailURL', 'imageURL', 'US_retailPrice',
       'US_dateFirstAvailable', 'US_dateLastAvailable', 'UK_retailPrice',
       'UK_dateFirstAvailable', 'UK_dateLastAvailable', 'CA_retailPrice',
       'CA_dateFirstAvailable', 'CA_dateLastAvailable', 'DE_retailPrice',
       'DE_dateFirstAvailable', 'DE_dateLastAvailable', 'height', 'width',
       'depth', 'weight'],
      dtype='object')

In [105]:
# columns which are not common don't hold any info that would be important for analysis, 
# because category of product or theme is more important than height and weight of the product

In [106]:
# 'inner' join keeps only columns common to all files
df = pd.concat(df_dict, axis=0, join='inner', ignore_index=True)

In [107]:
df.columns

Index(['setID', 'number', 'numberVariant', 'name', 'year', 'theme',
       'themeGroup', 'subtheme', 'category', 'released', 'pieces',
       'bricksetURL', 'rating', 'reviewCount', 'packagingType', 'availability',
       'thumbnailURL', 'imageURL'],
      dtype='object')

In [108]:
df.head()

,setID,number,numberVariant,name,year,theme,themeGroup,subtheme,category,released,pieces,bricksetURL,rating,reviewCount,packagingType,availability,thumbnailURL,imageURL
0,7693,1,8,Small house set,1970,Minitalia,Vintage,NaN,Normal,True,67.0,https://brickset.com/sets/1-8,0.0,0,{Not specified},{Not specified},https://images.brickset.com/sets/small/1-8.jpg,https://images.brickset.com/sets/images/1-8.jpg
1,7695,2,8,Medium house set,1970,Minitalia,Vintage,NaN,Normal,True,109.0,https://brickset.com/sets/2-8,0.0,0,{Not specified},{Not specified},https://images.brickset.com/sets/small/2-8.jpg,https://images.brickset.com/sets/images/2-8.jpg
2,7697,3,6,Medium house set,1970,Minitalia,Vintage,NaN,Normal,True,158.0,https://brickset.com/sets/3-6,0.0,1,{Not specified},{Not specified},https://images.brickset.com/sets/small/3-6.jpg,https://images.brickset.com/sets/images/3-6.jpg
3,7698,4,4,Large house set,1970,Minitalia,Vintage,NaN,Normal,True,233.0,https://brickset.com/sets/4-4,0.0,0,{Not specified},{Not specified},https://images.brickset.com/sets/small/4-4.jpg,https://images.brickset.com/sets/images/4-4.jpg
4,25534,4,6,Mini House and Vehicles,1970,Samsonite,Vintage,Model Maker,Normal,True,NaN,https://brickset.com/sets/4-6,0.0,0,{Not specified},{Not specified},NaN,NaN

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21546 entries, 0 to 21545
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   setID          21546 non-null  int64
 1   number         21546 non-null  object
 2   numberVariant  21546 non-null  int64
 3   name           21546 non-null  object
 4   year           21546 non-null  int64
 5   theme          21546 non-null  object
 6   themeGroup     21544 non-null  object
 7   subtheme       17941 non-null  object
 8   category       21546 non-null  object
 9   released       21546 non-null  bool
 10  pieces         17002 non-null  float64
 11  bricksetURL    21546 non-null  object
 12  rating         21546 non-null  float64
 13  reviewCount    21546 non-null  int64
 14  packagingType  21546 non-null  object
 15  availability   21546 non-null  object
 16  thumbnailURL   20544 non-null  object
 17  imageURL       20544 non-null  object
dtypes: bool(1), float64(2), int64(4), object(11)
memory usage: 2.8+ MB

In [110]:
df.isnull().sum()

setID               0
number              0
numberVariant       0
name                0
year                0
theme               0
themeGroup          2
subtheme         3605
category            0
released            0
pieces           4544
bricksetURL         0
rating              0
reviewCount         0
packagingType       0
availability        0
thumbnailURL     1002
imageURL         1002
dtype: int64

In [111]:
# View all distinct values in the 'Category' column
# df['theme'].unique()

In [112]:
# df['subtheme'].unique()

In [113]:
df = df.drop('pieces', axis=1)

In [114]:
df = df.drop('thumbnailURL', axis=1)
df = df.drop('imageURL', axis=1)

In [115]:
df = df.drop('bricksetURL', axis=1)

In [116]:
# Drops rows only if they have a missing value in 'themeGroup'
df = df.dropna(subset=['themeGroup'])

In [119]:
# Apply different string placeholders based on the column
df = df.fillna({'subtheme': 'Not Specified'})

In [120]:
df.isnull().sum()

setID            0
number           0
numberVariant    0
name             0
year             0
theme            0
themeGroup       0
subtheme         0
category         0
released         0
rating           0
reviewCount      0
packagingType    0
availability     0
dtype: int64

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21544 entries, 0 to 21545
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   setID          21544 non-null  int64
 1   number         21544 non-null  object
 2   numberVariant  21544 non-null  int64
 3   name           21544 non-null  object
 4   year           21544 non-null  int64
 5   theme          21544 non-null  object
 6   themeGroup     21544 non-null  object
 7   subtheme       21544 non-null  object
 8   category       21544 non-null  object
 9   released       21544 non-null  bool
 10  rating         21544 non-null  float64
 11  reviewCount    21544 non-null  int64
 12  packagingType  21544 non-null  object
 13  availability   21544 non-null  object
dtypes: bool(1), float64(1), int64(4), object(8)
memory usage: 2.3+ MB

In [123]:
from sqlalchemy import create_engine

username= 'root'
password = '123456'
host = 'localhost'
port = '3306'
database = 'projects'

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name = 'lego'
df.to_sql(table_name, engine, if_exists='replace',index=False)

pd.read_sql("SELECT * FROM lego LIMIT 5;", engine)

,setID,number,numberVariant,name,year,theme,themeGroup,subtheme,category,released,rating,reviewCount,packagingType,availability
0,7693,1,8,Small house set,1970,Minitalia,Vintage,Not Specified,Normal,1,0.0,0,{Not specified},{Not specified}
1,7695,2,8,Medium house set,1970,Minitalia,Vintage,Not Specified,Normal,1,0.0,0,{Not specified},{Not specified}
2,7697,3,6,Medium house set,1970,Minitalia,Vintage,Not Specified,Normal,1,0.0,1,{Not specified},{Not specified}
3,7698,4,4,Large house set,1970,Minitalia,Vintage,Not Specified,Normal,1,0.0,0,{Not specified},{Not specified}
4,25534,4,6,Mini House and Vehicles,1970,Samsonite,Vintage,Model Maker,Normal,1,0.0,0,{Not specified},{Not specified}